---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - clusterfilters
  - clusterinputs
  - clustermultilineparsers
  - clusteroutputs
  - clusterparsers
  verbs:
  - list
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - clusterfluentbitconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - collectors
  - filters
  - fluentbitconfigs
  - fluentbits
  - inputs
  - outputs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - filters
  - fluentbitconfigs
  - fluentbits
  - inputs
  - outputs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - filters
  - multilineparsers
  - outputs
  - parsers
  verbs:
  - list
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - fluentbitconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentd.fluent.io
  resources:
  - clusterfilters
  - clusterinputs
  - clusteroutputs
  verbs:
  - list
- apiGroups:
  - fluentd.fluent.io
  resources:
  - clusterfluentdconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentd.fluent.io
  resources:
  - filters
  - inputs
  - outputs
  verbs:
  - list
- apiGroups:
  - fluentd.fluent.io
  resources:
  - fluentdconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentd.fluent.io
  resources:
  - fluentdconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - fluentd.fluent.io
  resources:
  - fluentdconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fluentd.fluent.io
  resources:
  - fluentds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentd.fluent.io
  resources:
  - fluentds/finalizers
  verbs:
  - update
- apiGroups:
  - fluentd.fluent.io
  resources:
  - fluentds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
